using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace GS1ProductTracker.Shared.Constants
{
    public static class FieldMetaConstants
    {
        public const string CONTACTNAME = "CONTACTNAME";
        public const string INGREDIENTSTATEMENT = "INGREDIENTSTATEMENT";
        public const string MARKETINGMESSAGE = "MARKETINGMESSAGE";
        public const string IMAGE = "IMAGE";
        public const string DIMENSIONS = "DIMENSIONS";
        public const string PROCESSOR = "PROCESSOR";
        public const string BATTERY = "BATTERY";
        public const string MEMORY_RAM = "MEMORY_RAM";
        public const string MEMORY_ROM = "MEMORY_ROM";
        public const string SCREEN_SIZE = "SCREEN_SIZE";
        public const string SCREEN_RESOLUTION = "SCREEN_RESOLUTION";
        public const string CAMERA_BACK = "CAMERA_BACK";
        public const string CAMERA_FRONT = "CAMERA_FRONT";
        public const string BRAND = "BRAND";
        public const string SIZE = "SIZE";
        public const string COLOR = "COLOR";
        public const string WEIGTH = "WEIGTH";
        public const string OS = "OS";
        public const string DESCRIPTION = "DESCRIPTION";
        public const string NETCONTENT = "NETCONTENT";
        public const string NETCONTENTDRAINED = "NETCONTENTDRAINED";
        public const string NETCONTENTVOLUME = "NETCONTENTVOLUME";
        public const string DISAGGREGATEDNETCONTENT = "DISAGGREGATEDNETCONTENT";
        public const string CONSUMERINSTRUCTIONS = "CONSUMERINSTRUCTIONS";
        public const string ADDRESS = "ADDRESS";
        public const string COUNTRYORIGIN = "COUNTRYORIGIN";
        public const string RATIONS = "RATIONS";
        public const string REGULATEDPRODUCTNAME = "REGULATEDPRODUCTNAME";

        // Nutrients
        public const string NUTRIENT_ENERYKJ = "NUTRIENTENERYKJ";
        public const string NUTRIENT_ENERYKCAL = "NUTRIENTENERYKCAL";
        public const string NUTRIENT_FAT = "NUTRIENTFAT";
        public const string NUTRIENT_FATSATURATED = "NUTRIENTFATSATURATED";
        public const string NUTRIENT_SUGAR = "NUTRIENTSUGAR";
        public const string NUTRIENT_CHOAVL = "NUTRIENTCARBOHYDRATES";
        public const string NUTRIENT_FIBER = "NUTRIENT_FIBER";
        public const string NUTRIENT_SALTEQ = "NUTRIENTSALT";
        public const string NUTRIENT_PROTEIN = "NUTRIENTPROTEIN";
        public const string NUTRIENT_FAMSCIS = "NUTRIENT_FAMSCIS";
        public const string NUTRIENT_FAPUCIS = "NUTRIENT_FAPUCIS";
        public const string NUTRIENT_BIOT = "NUTRIENT_BIOT";
        public const string NUTRIENT_CA = "NUTRIENT_CA";
        public const string NUTRIENT_CLD = "NUTRIENT_CLD";
        public const string NUTRIENT_CR = "NUTRIENT_CR";
        public const string NUTRIENT_CU = "NUTRIENT_CU";
        public const string NUTRIENT_FD = "NUTRIENT_FD";
        public const string NUTRIENT_FE = "NUTRIENT_FE";
        public const string NUTRIENT_FOLDFE = "NUTRIENT_FOLDFE";
        public const string NUTRIENT_ID = "NUTRIENT_ID";
        public const string NUTRIENT_K = "NUTRIENT_K";
        public const string NUTRIENT_MG = "NUTRIENT_MG";
        public const string NUTRIENT_MN = "NUTRIENT_MN";
        public const string NUTRIENT_MO = "NUTRIENT_MO";
        public const string NUTRIENT_NIA = "NUTRIENT_NIA";
        public const string NUTRIENT_P = "NUTRIENT_P";
        public const string NUTRIENT_PANTAC = "NUTRIENT_PANTAC";
        public const string NUTRIENT_POLYL = "NUTRIENT_POLYL";
        public const string NUTRIENT_RIBF = "NUTRIENT_RIBF";
        public const string NUTRIENT_SE = "NUTRIENT_SE";
        public const string NUTRIENT_STARCH = "NUTRIENT_STARCH";
        public const string NUTRIENT_THIA = "NUTRIENT_THIA";
        public const string NUTRIENT_VITA = "NUTRIENT_VITA";
        public const string NUTRIENT_VITB12 = "NUTRIENT_VITB12";
        public const string NUTRIENT_VITB6 = "NUTRIENT_VITB6";
        public const string NUTRIENT_VITC = "NUTRIENT_VITC";
        public const string NUTRIENT_VITD = "NUTRIENT_VITD";
        public const string NUTRIENT_VITE = "NUTRIENT_VITE";
        public const string NUTRIENT_VITK = "NUTRIENT_VITK";
        public const string NUTRIENT_ZN = "NUTRIENT_ZN";

        // Names
        public const string NAME_CONTACTNAME = "Nome do operador";
        public const string NAME_INGREDIENTSTATEMENT = "Lista de ingredientes do rótulo";
        public const string NAME_MARKETINGMESSAGE = "Informações de marketing";
        public const string NAME_NETCONTENT = "Net Content";
        public const string NAME_NETCONTENTVOLUME = "Net Content(Volume)";
        public const string NAME_DISAGGREGATEDNETCONTENT = "Disaggregated Net Content";
        public const string NAME_CONSUMERINSTRUCTIONS = "Consumer instructions";
        public const string NAME_ADRESS = "Address";
        public const string NAME_COUNTRYORIGIN = "Country of origin";
        public const string NAME_RATIONS = "Number of rations";
        public const string NAME_IMAGE = "IMAGE";
        public const string NAME_DIMENSIONS = "Dimensões (A x L x P) (mm)";
        public const string NAME_PROCESSOR = "Processador";
        public const string NAME_BATTERY = "Bateria (mAh)";
        public const string NAME_MEMORY_RAM = "Memória RAM (GB)";
        public const string NAME_MEMORY_ROM = "Memória ROM (GB)";
        public const string NAME_SCREEN_SIZE = "Ecrã (Polegadas)";
        public const string NAME_SCREEN_RESOLUTION = "Resolução Ecrã";
        public const string NAME_CAMERA_BACK = "Camera Traseira";
        public const string NAME_CAMERA_FRONT = "Camera Frontal";
        public const string NAME_BRAND = "Marca";
        public const string NAME_SIZE = "Tamanho(s)";
        public const string NAME_COLOR = "Cores";
        public const string NAME_WEIGTH = "Peso";
        public const string NAME_OS = "Sistema Operativo";
        public const string NAME_DESCRIPTION = "Descrição";
        public const string NAME_NETCONTENTDRAINED = "Drained Net Content";
        public const string NAME_REGULATEDPRODUCTNAME = "Regulated Product Name";

        // Names - Nutrients
        public const string NAME_NUTRIENT_ENERYKJ = "Energia KJ";
        public const string NAME_NUTRIENT_ENERYKCAL = "Energia KCal";
        public const string NAME_NUTRIENT_FAT = "Gordura";
        public const string NAME_NUTRIENT_FATSATURATED = "Gordura saturada";
        public const string NAME_NUTRIENT_SUGAR = "Açúcar";
        public const string NAME_NUTRIENT_CHOAVL = "Hitratos de carbono";
        public const string NAME_NUTRIENT_FIBER = "Fibra";
        public const string NAME_NUTRIENT_SALTEQ = "Sal";
        public const string NAME_NUTRIENT_FAMSCIS = "Monounsaturated fatty acids";
        public const string NAME_NUTRIENT_FAPUCIS = "Polyunsaturated fatty acids";
        public const string NAME_NUTRIENT_PRO = "Proteins";
        public const string NAME_NUTRIENT_BIOT = "Biotin";
        public const string NAME_NUTRIENT_CA = "Cinnamyl alcohol";
        public const string NAME_NUTRIENT_CLD = "Chlorine";
        public const string NAME_NUTRIENT_CR = "Chrome";
        public const string NAME_NUTRIENT_CU = "Copper";
        public const string NAME_NUTRIENT_FD = "Fluorine";
        public const string NAME_NUTRIENT_FE = "Iron";
        public const string NAME_NUTRIENT_FOLDFE = "Folic Acid";
        public const string NAME_NUTRIENT_ID = "Iodine";
        public const string NAME_NUTRIENT_K = "Potassium";
        public const string NAME_NUTRIENT_MG = "Magnesium";
        public const string NAME_NUTRIENT_MN = "Manganese";
        public const string NAME_NUTRIENT_MO = "Molybdenum";
        public const string NAME_NUTRIENT_NIA = "Niacin";
        public const string NAME_NUTRIENT_P = "Phosphorus";
        public const string NAME_NUTRIENT_PANTAC = "Pantothenic acid";
        public const string NAME_NUTRIENT_POLYL = "Polyols";
        public const string NAME_NUTRIENT_RIBF = "Riboflavin";
        public const string NAME_NUTRIENT_SE = "Selenium";
        public const string NAME_NUTRIENT_STARCH = "Starch";
        public const string NAME_NUTRIENT_THIA = "Thiamine";
        public const string NAME_NUTRIENT_VITA = "Vitamin A";
        public const string NAME_NUTRIENT_VITB12 = "Vitamin B12";
        public const string NAME_NUTRIENT_VITB6 = "Vitamin B6";
        public const string NAME_NUTRIENT_VITC = "Vitamin C";
        public const string NAME_NUTRIENT_VITD = "Vitamin D";
        public const string NAME_NUTRIENT_VITE = "Vitamin E";
        public const string NAME_NUTRIENT_VITK = "Vitamin K";
        public const string NAME_NUTRIENT_ZN = "Zinc";
    }
}
