namespace GS1ProductTracker.Shared.Constants
{
    public static class ImageComparisonConstants
    {
        public static readonly string SENTENCE_FIRST_VALIDATION_FAIL = "FIRST_VALIDATION_FAIL";
        public static readonly string SENTENCE_FIRST_VALIDATION_SUCCESS_WITH_GOOD_RESOLUTION = "FIRST_VALIDATION_SUCCESS_WITH_GOOD_RESOLUTION";
        public static readonly string SENTENCE_FIRST_VALIDATION_SUCCESS_WITH_BAD_RESOLUTION = "FIRST_VALIDATION_SUCCESS_WITH_BAD_RESOLUTION";
        public static readonly string SENTENCE_SECOND_VALIDATION_SUCCESS_WITH_GOOD_RESOLUTION = "SECOND_VALIDATION_SUCCESS_WITH_GOOD_RESOLUTION";
        public static readonly string SENTENCE_SECOND_VALIDATION_SUCCESS_WITH_BAD_RESOLUTION = "SECOND_VALIDATION_SUCCESS_WITH_BAD_RESOLUTION";
        public static readonly string SENTENCE_THIRD_VALIDATION_SUCCESS_WITH_GOOD_RESOLUTION = "THIRD_VALIDATION_SUCCESS_WITH_GOOD_RESOLUTION";
        public static readonly string SENTENCE_THIRD_VALIDATION_SUCCESS_WITH_BAD_RESOLUTION = "THIRD_VALIDATION_SUCCESS_WITH_BAD_RESOLUTION";

        public static readonly string THRESHOLD_FIRST_VALIDATION = "FIRST_VALIDATION";
        public static readonly string THRESHOLD_SECOND_VALIDATION = "SECOND_VALIDATION";
        public static readonly string THRESHOLD_THIRD_VALIDATION = "THIRD_VALIDATION";
    }
}
